config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :projects, expect: [:index, :show, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to root_path, notice: 'Project created!'
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="container">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <%= link_to "Demo app", root_path, class: 'navbar-brand' %>
    </div>
  </nav>
</header>

<div class="container">
  <%= flash_messages if show_layout_flash? %>

  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project, wrapper_mappings: { boolean: :vertical_boolean } do |f| %>
  <%= f.input :name %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>New Project</h2>
    <%= render "form" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <h1>Demo app</h1>
    <p><%= link_to "New Project", new_project_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
</div>